# environment.yml
name: deepmgo
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.21.0
  - pandas>=1.3.0
  - tensorflow>=2.8.0
  - plotly>=5.3.0
  - matplotlib>=3.4.0
  - scikit-learn>=0.24.0
  - pip
  - pip:
    - padelpy>=0.1.9
    - shiny>=0.2.8
    - nest-asyncio>=1.5.0
